# Generated by Django 5.0.2 on 2024-03-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="aircrafttable",
            fields=[
                ("aircraftId", models.AutoField(primary_key=True, serialize=False)),
                ("tailNumber", models.CharField(max_length=45, null=True)),
                ("shipNumber", models.IntegerField(null=True)),
                ("Type", models.CharField(max_length=4, null=True)),
                ("status", models.CharField(max_length=45, null=True)),
                ("location", models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="airporttable",
            fields=[
                ("airportId", models.AutoField(primary_key=True, serialize=False)),
                ("airportCode", models.CharField(max_length=4)),
                ("lattitude", models.CharField(max_length=5)),
                ("longitude", models.CharField(max_length=5)),
                ("numAircraft", models.IntegerField(null=True)),
                ("userId", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="movementtable",
            fields=[
                ("movementId", models.AutoField(primary_key=True, serialize=False)),
                ("airportId", models.IntegerField(null=True)),
                ("arrivalDate", models.CharField(max_length=8)),
                ("departureDate", models.CharField(max_length=8)),
                ("aircraftId", models.IntegerField(null=True)),
                ("userId", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="userprofile",
            fields=[
                ("userId", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=45)),
                ("password", models.CharField(max_length=45)),
                ("role", models.CharField(max_length=45)),
            ],
        ),
    ]
