# Generated by Django 5.0.3 on 2024-03-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airporttable",
            old_name="lattitude",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="movementtable",
            old_name="airportId",
            new_name="arrivalAirportId",
        ),
        migrations.RemoveField(
            model_name="aircrafttable",
            name="Type",
        ),
        migrations.RemoveField(
            model_name="aircrafttable",
            name="shipNumber",
        ),
        migrations.AddField(
            model_name="aircrafttable",
            name="aircraftType",
            field=models.CharField(
                choices=[
                    ("A320", "A320"),
                    ("A321", "A321"),
                    ("A330", "A330"),
                    ("A350", "A350"),
                    ("B737", "B737"),
                    ("B757", "B757"),
                    ("B767", "B767"),
                    ("B787", "B787"),
                    ("B777", "B777"),
                ],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movementtable",
            name="originAirportId",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("corporate", "Corporate"),
                    ("facility", "Facility"),
                ],
                max_length=9,
                null=True,
            ),
        ),
    ]
